# Generated by Django 2.2.5 on 2020-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCrypto',
            fields=[
                ('photo_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('photo_path', models.TextField()),
            ],
        ),
    ]
